# installation debian

source "azure-arm" "autogenerated_1"  {
subscription_id                   = "${env("DEBIAN_AZURE_SUBSCRIPTION_ID")}"
build_resource_group_name         = "TestProxy"
managed_image_resource_group_name = "TestProxy"
managed_image_name                = "Debian-client"
os_type                           = "Linux"
image_publisher                   = "Debian"
image_offer                       = "Debian-11"
image_sku                         = "11-backports-gen2"

use_interactive_auth = true

  azure_tags = {
    task = "Image deployment"
  }

  vm_size                           = "Standard_B1ls"
}


build {
  sources = ["source.azure-arm.autogenerated_1"]

}