# installation debian

source "azure-arm" "autogenerated_1"  {
subscription_id                   = "${env("NGINX_AZURE_SUBSCRIPTION_ID")}"
build_resource_group_name         = "TestProxy"
managed_image_resource_group_name = "TestProxy"
managed_image_name                = "Nginx"
os_type                           = "Linux"
image_publisher                   = "Debian"
image_offer                       = "Debian-11"
image_sku                         = "11-backports-gen2"

use_interactive_auth = true

  azure_tags = {
    task = "Image deployment"
  }

  vm_size                           = "Standard_B1ls"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

 
# installation nginx

  provisioner "shell" {
    inline= [
      "sudo apt-get update && sudo apt-get upgrade -y",
      "sudo apt-get -y install nginx",
      "sudo systemctl start nginx",
      "sudo systemctl enable nginx",
      "sudo systemctl restart nginx"
    ]
  }
}